name: 发布到PyPI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: 构建包
      run: python -m build
    
    - name: 验证包
      run: twine check dist/*
    
    - name: 发布到PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*